name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read

env:
  DEVELOPER_DIR: /Applications/Xcode_27.0.app

jobs:
  build:
    name: Build for ${{ matrix.project }}
    # ref: https://github.com/actions/runner-images/issues/14404
    runs-on: xcode-27
    strategy:
      fail-fast: false
      matrix:
        project: ["production", "develop", "catalog"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Build for ${{ matrix.project }}
        run: make build-debug-${{ matrix.project }}

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.1
    with:
      api_breakage_check_enabled: false
      docs_check_enabled: false
      license_header_check_enabled: false
      format_check_enabled: false
