name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_tests_ios:
    name: Build iOS Tests for ${{ matrix.project }}
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.1
    strategy:
      matrix:
        project: ["production", "develop"]
    with:
      enable_linux_checks: false
      enable_windows_checks: false
      enable_ios_checks: true
      ios_host_xcode_versions: "[\"26.1\"]"
      ios_host_versions: "[\"sequoia\"]"
      ios_build_command: make build-debug-${{ matrix.project }}

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.1
    with:
      api_breakage_check_enabled: false
      docs_check_enabled: false
      license_header_check_enabled: false
      format_check_enabled: false
